# -*- coding: utf-8 -*-
"""travel_time.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rD6IBxbFi7-t6GPDSFGUfhQYHDxpVubV
"""

import requests
import datetime
import pytz
import csv
import time

# Google Maps API Key
API_KEY = "AIzaSyDeU40JTOwi2EtX38E8ZNLrSx_HYNfE1os"

# Origin & Destination
ORIGIN = "Unit no. 304, Sentinel Hiranandani Business Park, Powai, Mumbai, Maharashtra 400076"
DESTINATION = "New Mahada Colony, SV Patel Nagar, Andheri West, Mumbai, Maharashtra 400061"

# API URL
BASE_URL = "https://maps.googleapis.com/maps/api/directions/json"

# Set IST timezone
ist = pytz.timezone("Asia/Kolkata")

# CSV File Name
CSV_FILE = "travel_time_log.csv"

# Interval (in seconds) → Example: Every 10 minutes
INTERVAL = 1 * 60

# Function to fetch travel time
def get_travel_time():
    params = {
        "origin": ORIGIN,
        "destination": DESTINATION,
        "departure_time": "now",
        "traffic_model": "best_guess",
        "key": API_KEY
    }

    response = requests.get(BASE_URL, params=params)
    data = response.json()

    if "routes" in data and data["routes"]:
        duration = data["routes"][0]["legs"][0]["duration_in_traffic"]["text"]
        current_time_ist = datetime.datetime.now(pytz.utc).astimezone(ist).strftime('%Y-%m-%d %H:%M:%S')

        # Print the result
        print(f"IST Time: {current_time_ist}, Travel Duration: {duration}")

        # Append data to CSV
        with open(CSV_FILE, mode="a", newline="") as file:
            writer = csv.writer(file)
            writer.writerow([current_time_ist, duration])
    else:
        print("Error fetching data:", data)

# Initialize CSV file with headers if running for the first time
with open(CSV_FILE, mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Timestamp (IST)", "Travel Duration"])

# Run script at intervals
while True:
    get_travel_time()
    time.sleep(INTERVAL)  # Wait for the next cycle