name: Run Travel Time Logger

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install requests pytz

      - name: Run Python Script
        run: python travel_time.py
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Commit & Push CSV File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add travel_time_log.csv
          git commit -m "Update travel time log [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "No changes to push"


