name: Travel Time Logger

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  log_travel_time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run travel time logger
        run: python travel_time.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add travel_time_log.csv
          git commit -m "Update travel time log [skip ci]" || echo "No changes to commit"
          git push






